### ISSUE TITLE
Smarty template engine

### ISSUE THREAD

**Issue by poseso** [zentraedi/codeigniter3-boilerplate#1]
I'm having problems trying to integrate Smarty as my template engine with your boilerplate, can you integrate to your boilerplate Smarty? and a look to the SQL file for this to work ?

I'd like to have:

Codeigniter 3.0
Modular Extensions
php-activerecord
CodeIgniter-Ion-Auth
dompdf
Excel reader
and Smarty for the template engine,

I don't know if this is the right place to request features for your boilerplate, but if its not, i'm really sorry and tell me where should i.

Thanks

**Comment by zentraedi** [comment]
I added support for Smarty templating engine in this branch:

https://github.com/zentraedi/codeigniter3-boilerplate/tree/with-smarty

Let me know if this works fine and nice with all the others components...

Cheers!

**Comment by poseso** [comment]
I will try it out and let you know! thanks in advanced!

**Comment by poseso** [comment]
everything is working perfectly! all components and everything!  Thank you!!!

**Comment by zentraedi** [comment]
Glad it worked!

Took everything from here: https://github.com/Vheissu/Ci-Smarty for further reference.
